In [12]:
# importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
# Reading the dataset
dataset = pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [14]:
# Change categorical data to nominal
dataset = pd.get_dummies(dataset, drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [15]:
# Split independent and dependent variables
independent = dataset[["Age", "EstimatedSalary", "Gender_Male"]]
dependent = dataset[["Purchased"]]

In [16]:
# Split into training set and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [17]:
# Import StandardScaler to standardize the features
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler object
sc = StandardScaler()

# Fit the scaler using the training data and transform the training data
# Each feature will be scaled to have mean = 0 and standard deviation = 1
x_train = sc.fit_transform(x_train)

# Use the same scaler fitted on training data to transform the test data
# We use only transform() here to avoid data leakage from the test set
x_test = sc.transform(x_test)

In [18]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

param_grid = {
    'kernel': [
        'linear',
        'rbf',
        'poly',
        'sigmoid'
    ],
    'gamma': [
        'auto',
        'scale'
    ],
    'C': [
        10, 100, 1000, 2000, 3000
    ]
}

grid = GridSearchCV(
    SVC(probability=True), 
    param_grid, 
    refit=True, 
    verbose=3,
    cv=5,
    n_jobs=-1,
    scoring='f1_weighted'
)

grid.fit(x_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=5, estimator=SVC(probability=True), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             scoring='f1_weighted', verbose=3)

In [20]:
# print best parameter after tuning
print(grid.best_params_)

re = grid.cv_results_
print(re)

grid_predictions = grid.predict(x_test)

# print confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
print("Confusion Matrix:\n", cm) 

# print classification report
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
print("CFM Report:\n ", clf_report)

{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}
{'mean_fit_time': array([0.00721874, 0.00561824, 0.0087409 , 0.00464377, 0.0052    ,
       0.00492716, 0.00659003, 0.0042417 , 0.01643257, 0.00847764,
       0.02750726, 0.00536761, 0.01997004, 0.00940876, 0.0252852 ,
       0.00500836, 0.10521808, 0.01983814, 0.15900211, 0.00631785,
       0.1206923 , 0.0234055 , 0.17819996, 0.00725217, 0.25287466,
       0.03837314, 0.35048881, 0.00619402, 0.21757512, 0.03650036,
       0.37700605, 0.00577817, 0.29470568, 0.05034218, 0.59892302,
       0.00636592, 0.33495393, 0.05925841, 0.64041271, 0.00828552]), 'std_fit_time': array([0.00163564, 0.00164893, 0.00168756, 0.0014797 , 0.00039269,
       0.00137087, 0.00074636, 0.00107306, 0.00263656, 0.00197743,
       0.01088963, 0.00066995, 0.0043765 , 0.00114088, 0.00779833,
       0.00084957, 0.02485234, 0.00106845, 0.03969185, 0.00177873,
       0.031706  , 0.00458954, 0.07996045, 0.00200818, 0.06624807,
       0.00830263, 0.12025144, 0.00243154, 0.04905601, 0.0053392 ,
       0.08734378, 0.00156078, 0.02669891, 0.00884893, 0.17261552,
       0.00188269, 0.08471118, 0.00785927, 0.23941434, 0.00309517]), 'mean_score_time': array([0.00357642, 0.00489383, 0.00425344, 0.00411482, 0.00336342,
       0.00407906, 0.00419283, 0.00399885, 0.00429773, 0.00414515,
       0.00382495, 0.00391822, 0.00397015, 0.00442076, 0.00443392,
       0.00383472, 0.00441189, 0.0040936 , 0.00469437, 0.00396791,
       0.00490742, 0.00461555, 0.00464897, 0.00438595, 0.00494895,
       0.00498109, 0.00457616, 0.00438857, 0.00520768, 0.00471282,
       0.00510554, 0.00470839, 0.00416546, 0.00597425, 0.00655169,
       0.00477691, 0.00438886, 0.00543509, 0.00447001, 0.00499949]), 'std_score_time': array([0.00103547, 0.00203781, 0.00112079, 0.00109023, 0.00055938,
       0.00103198, 0.00103344, 0.00046935, 0.00049092, 0.00092555,
       0.00063106, 0.00052683, 0.00032376, 0.00079952, 0.00071106,
       0.00075309, 0.0005709 , 0.0006595 , 0.00077234, 0.00120974,
       0.00096345, 0.00120024, 0.00133433, 0.00111648, 0.00113877,
       0.00103615, 0.0015416 , 0.00113531, 0.00127601, 0.00070797,
       0.00166759, 0.00146637, 0.0004089 , 0.00182176, 0.00164915,
       0.00095296, 0.0012918 , 0.00189069, 0.00165585, 0.00181605]), 'param_C': masked_array(data=[10, 10, 10, 10, 10, 10, 10, 10, 100, 100, 100, 100,
                   100, 100, 100, 100, 1000, 1000, 1000, 1000, 1000, 1000,
                   1000, 1000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
                   2000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=999999), 'param_gamma': masked_array(data=['auto', 'auto', 'auto', 'auto', 'scale', 'scale',
                   'scale', 'scale', 'auto', 'auto', 'auto', 'auto',
                   'scale', 'scale', 'scale', 'scale', 'auto', 'auto',
                   'auto', 'auto', 'scale', 'scale', 'scale', 'scale',
                   'auto', 'auto', 'auto', 'auto', 'scale', 'scale',
                   'scale', 'scale', 'auto', 'auto', 'auto', 'auto',
                   'scale', 'scale', 'scale', 'scale'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_kernel': masked_array(data=['linear', 'rbf', 'poly', 'sigmoid', 'linear', 'rbf',
                   'poly', 'sigmoid', 'linear', 'rbf', 'poly', 'sigmoid',
                   'linear', 'rbf', 'poly', 'sigmoid', 'linear', 'rbf',
                   'poly', 'sigmoid', 'linear', 'rbf', 'poly', 'sigmoid',
                   'linear', 'rbf', 'poly', 'sigmoid', 'linear', 'rbf',
                   'poly', 'sigmoid', 'linear', 'rbf', 'poly', 'sigmoid',
                   'linear', 'rbf', 'poly', 'sigmoid'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 10, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 100, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 100, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 1000, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 2000, 'gamma': 'scale', 'kernel': 'sigmoid'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}, {'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}, {'C': 3000, 'gamma': 'scale', 'kernel': 'sigmoid'}], 'split0_test_score': array([0.77629048, 0.86747844, 0.79962013, 0.76267713, 0.77629048,
       0.86747844, 0.79962013, 0.76267713, 0.77629048, 0.86747844,
       0.82209189, 0.80892657, 0.77629048, 0.86747844, 0.82209189,
       0.80892657, 0.77629048, 0.82626263, 0.82209189, 0.79175183,
       0.77629048, 0.84714126, 0.82209189, 0.80892657, 0.77629048,
       0.82626263, 0.82209189, 0.79175183, 0.77629048, 0.82626263,
       0.82209189, 0.80892657, 0.77629048, 0.82626263, 0.82209189,
       0.79175183, 0.77629048, 0.82626263, 0.82209189, 0.80892657]), 'split1_test_score': array([0.79094947, 0.88679245, 0.80839191, 0.73891582, 0.79094947,
       0.88679245, 0.80839191, 0.73891582, 0.79094947, 0.88679245,
       0.78728354, 0.7149311 , 0.79094947, 0.88679245, 0.78728354,
       0.7149311 , 0.79094947, 0.86696784, 0.76555329, 0.7149311 ,
       0.79094947, 0.86696784, 0.76555329, 0.7149311 , 0.79094947,
       0.86696784, 0.76555329, 0.7149311 , 0.79094947, 0.86696784,
       0.76555329, 0.7149311 , 0.79094947, 0.86696784, 0.76555329,
       0.7149311 , 0.79094947, 0.86696784, 0.76555329, 0.7149311 ]), 'split2_test_score': array([0.69823494, 0.86970866, 0.78794275, 0.65579515, 0.69823494,
       0.86970866, 0.78794275, 0.75317976, 0.69823494, 0.87036224,
       0.76655568, 0.6337193 , 0.69823494, 0.87036224, 0.76655568,
       0.69811321, 0.69823494, 0.8515274 , 0.76655568, 0.69811321,
       0.69823494, 0.8515274 , 0.76655568, 0.69811321, 0.69823494,
       0.8515274 , 0.76655568, 0.69811321, 0.69823494, 0.8515274 ,
       0.76655568, 0.69811321, 0.69823494, 0.8515274 , 0.76655568,
       0.69811321, 0.69823494, 0.8515274 , 0.76655568, 0.69811321]), 'split3_test_score': array([0.92351003, 0.94416086, 0.9245283 , 0.79628353, 0.92351003,
       0.94416086, 0.9245283 , 0.77806673, 0.92351003, 0.94416086,
       0.9245283 , 0.7184975 , 0.92351003, 0.94416086, 0.9245283 ,
       0.79628353, 0.92351003, 0.92527158, 0.9245283 , 0.79628353,
       0.92351003, 0.92527158, 0.9245283 , 0.79628353, 0.92351003,
       0.88679245, 0.9245283 , 0.79628353, 0.92351003, 0.88679245,
       0.9245283 , 0.79628353, 0.92351003, 0.84702007, 0.9245283 ,
       0.79628353, 0.92351003, 0.84702007, 0.9245283 , 0.79628353]), 'split4_test_score': array([0.90174425, 0.94304148, 0.90174425, 0.76655568, 0.90174425,
       0.94304148, 0.90174425, 0.76655568, 0.90174425, 0.94304148,
       0.90174425, 0.76655568, 0.90174425, 0.94304148, 0.90174425,
       0.76655568, 0.90174425, 0.92351003, 0.90174425, 0.76655568,
       0.90174425, 0.92351003, 0.90174425, 0.76655568, 0.90174425,
       0.90361034, 0.90174425, 0.76655568, 0.90174425, 0.90361034,
       0.90174425, 0.76655568, 0.90174425, 0.88327784, 0.90174425,
       0.76655568, 0.90174425, 0.88327784, 0.90174425, 0.76655568]), 'mean_test_score': array([0.81814583, 0.90223638, 0.84444547, 0.74404546, 0.81814583,
       0.90223638, 0.84444547, 0.75987902, 0.81814583, 0.90236709,
       0.84044073, 0.72852603, 0.81814583, 0.90236709, 0.84044073,
       0.75696202, 0.81814583, 0.8787079 , 0.83609468, 0.75352707,
       0.81814583, 0.88288362, 0.83609468, 0.75696202, 0.81814583,
       0.86703213, 0.83609468, 0.75352707, 0.81814583, 0.86703213,
       0.83609468, 0.75696202, 0.81814583, 0.85501116, 0.83609468,
       0.75352707, 0.81814583, 0.85501116, 0.83609468, 0.75696202]), 'std_test_score': array([0.08361871, 0.0344308 , 0.05691772, 0.04774326, 0.08361871,
       0.0344308 , 0.05691772, 0.01317221, 0.08361871, 0.03430808,
       0.0623702 , 0.05862459, 0.08361871, 0.03430808, 0.0623702 ,
       0.04374543, 0.08361871, 0.03950322, 0.06654053, 0.04004831,
       0.08361871, 0.03452908, 0.06654053, 0.04374543, 0.08361871,
       0.02694806, 0.06654053, 0.04004831, 0.08361871, 0.02694806,
       0.06654053, 0.04374543, 0.08361871, 0.01920646, 0.06654053,
       0.04004831, 0.08361871, 0.01920646, 0.06654053, 0.04374543]), 'rank_test_score': array([21,  3, 11, 39, 21,  3, 11, 31, 21,  1, 13, 40, 21,  1, 13, 32, 21,
        6, 15, 36, 21,  5, 15, 32, 21,  7, 15, 36, 21,  7, 15, 32, 21,  9,
       15, 36, 21,  9, 15, 32], dtype=int32)}
Confusion Matrix:
 [[80  5]
 [ 7 42]]
CFM Report:
                precision    recall  f1-score   support

           0       0.92      0.94      0.93        85
           1       0.89      0.86      0.88        49

    accuracy                           0.91       134
   macro avg       0.91      0.90      0.90       134
weighted avg       0.91      0.91      0.91       134

In [21]:
# Import f1_score to calculate the F1-score
from sklearn.metrics import f1_score

# Calculate the weighted F1-score
# y_test          -> Actual values
# grid_predictions -> Predictions made by the best GridSearchCV model
# average='weighted' -> Calculate F1 for each class and weight it based on class size
f1_weighted = f1_score(
    y_test,
    grid_predictions,
    average='weighted'
)

# Display the best parameters found by GridSearchCV
# and the F1-score obtained on the test data
print(
    "The f1_weighted value for best parameter {}:".format(grid.best_params_),
    f1_weighted
)


# Import roc_auc_score to calculate ROC-AUC
from sklearn.metrics import roc_auc_score

# Calculate ROC-AUC score
# ROC-AUC evaluates how well your model can distinguish between the two classes.
# grid.predict_proba(x_test) returns probabilities for each class
# [:, 1] selects the probability of class 1
roc_auc_score(
    y_test,
    # Get probability of class 1
    grid.predict_proba(x_test)[:, 1]
)

The f1_weighted value for best parameter {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}: 0.9100355779243318

0.9539015606242497